# Generated by Django 4.2.4 on 2024-02-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_moudel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
