# Generated by Django 4.2.4 on 2024-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_moudel', '0002_user_email_active_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
