# Generated by Django 4.2.4 on 2024-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_moudel', '0003_alter_user_options_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
