# Generated by Django 4.2.4 on 2024-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_moudel', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.EmailField(max_length=254),
        ),
    ]
