# Generated by Django 4.2.4 on 2024-02-08 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account_moudel', '0010_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
