# Generated by Django 4.2.4 on 2024-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_moudel', '0011_remove_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
