# Generated by Django 3.2.8 on 2024-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_moudel', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.FileField(default=123, upload_to='images'),
            preserve_default=False,
        ),
    ]
