# Generated by Django 4.2 on 2024-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_moudel', '0015_remove_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active_code',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_active_code',
            field=models.IntegerField(default=4568),
            preserve_default=False,
        ),
    ]
