# Generated by Django 5.1.3 on 2024-11-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_moudel', '0018_alter_user_phone_active_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_active_code',
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_moudel.user')),
            ],
        ),
    ]
