# Generated by Django 5.1.3 on 2024-12-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_moudel', '0019_remove_user_phone_active_code_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
